services:
  elastic-1:
    image: "bitnami/elasticsearch:8.17.1"
    container_name: elastic-1
    environment:
      BITNAMI_DEBUG: true
      ELASTICSEARCH_NODE_NAME: elastic-1
      ELASTICSEARCH_CLUSTER_NAME: elastic
      ELASTICSEARCH_PASSWORD: qwerty
      ELASTICSEARCH_ENABLE_SECURITY: true
      ELASTICSEARCH_ENABLE_REST_TLS: false
      ELASTICSEARCH_TLS_VERIFICATION_MODE: none
      ELASTICSEARCH_TRANSPORT_TLS_KEYSTORE_LOCATION: /opt/bitnami/elasticsearch/config/certs/ca-elastic.p12
      ELASTICSEARCH_TRANSPORT_TLS_TRUSTSTORE_LOCATION: /opt/bitnami/elasticsearch/config/certs/ca-elastic.p12
      ELASTICSEARCH_CLUSTER_HOSTS: elastic-1,elastic-2,elastic-3
      ELASTICSEARCH_HEAP_SIZE: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail --user elastic:qwerty localhost:9200/_cluster/health?local=true || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 10
    volumes:
      - elastic-1:/bitnami
      - ./certs/:/opt/bitnami/elasticsearch/config/certs/

  elastic-2:
    image: "bitnami/elasticsearch:8.17.1"
    container_name: elastic-2
    environment:
      ELASTICSEARCH_NODE_NAME: elastic-2
      ELASTICSEARCH_CLUSTER_NAME: elastic
      ELASTICSEARCH_PASSWORD: qwerty
      ELASTICSEARCH_ENABLE_SECURITY: true
      ELASTICSEARCH_ENABLE_REST_TLS: false
      ELASTICSEARCH_TLS_VERIFICATION_MODE: none
      ELASTICSEARCH_TRANSPORT_TLS_KEYSTORE_LOCATION: /opt/bitnami/elasticsearch/config/certs/ca-elastic.p12
      ELASTICSEARCH_TRANSPORT_TLS_TRUSTSTORE_LOCATION: /opt/bitnami/elasticsearch/config/certs/ca-elastic.p12
      ELASTICSEARCH_CLUSTER_HOSTS: elastic-1,elastic-2,elastic-3
      ELASTICSEARCH_HEAP_SIZE: 1g
    ports:
      - "9201:9200"
      - "9301:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail --user elastic:qwerty localhost:9200/_cluster/health?local=true || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 10
    volumes:
      - elastic-2:/bitnami
      - ./certs/:/opt/bitnami/elasticsearch/config/certs/

  elastic-3:
    image: "bitnami/elasticsearch:8.17.1"
    container_name: elastic-3
    environment:
      ELASTICSEARCH_NODE_NAME: elastic-3
      ELASTICSEARCH_CLUSTER_NAME: elastic
      ELASTICSEARCH_PASSWORD: qwerty
      ELASTICSEARCH_ENABLE_SECURITY: true
      ELASTICSEARCH_ENABLE_REST_TLS: false
      ELASTICSEARCH_TLS_VERIFICATION_MODE: none
      ELASTICSEARCH_TRANSPORT_TLS_KEYSTORE_LOCATION: /opt/bitnami/elasticsearch/config/certs/ca-elastic.p12
      ELASTICSEARCH_TRANSPORT_TLS_TRUSTSTORE_LOCATION: /opt/bitnami/elasticsearch/config/certs/ca-elastic.p12
      ELASTICSEARCH_CLUSTER_HOSTS: elastic-1,elastic-2,elastic-3
      ELASTICSEARCH_HEAP_SIZE: 1g
    ports:
      - "9202:9200"
      - "9302:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail --user elastic:qwerty localhost:9200/_cluster/health?local=true || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 10
    volumes:
      - elastic-3:/bitnami
      - ./certs/:/opt/bitnami/elasticsearch/config/certs/

  kibana:
    image: "bitnami/kibana:8.17.1"
    container_name: kibana
    environment:
      KIBANA_CREATE_USER: yes
      KIBANA_PASSWORD: qwerty
      KIBANA_ELASTICSEARCH_PASSWORD: qwerty
      KIBANA_ELASTICSEARCH_URL: elastic-1
    ports:
      - "5601:5601"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:5601/api/status || exit 1" ]
      interval: 15s
      timeout: 15s
      retries: 5
    volumes:
      - kibana:/bitnami/kibana
    depends_on:
      elastic-1:
        condition: service_healthy
      elastic-2:
        condition: service_healthy
      elastic-3:
        condition: service_healthy

volumes:
  elastic-1:
  elastic-2:
  elastic-3:
  kibana:
