services:
  elastic:
    image: "bitnami/elasticsearch:8.17.1"
    container_name: elastic
    environment:
      ELASTICSEARCH_NODE_NAME: elastic
      ELASTICSEARCH_CLUSTER_NAME: elastic
      ELASTICSEARCH_ENABLE_SECURITY: false
      ELASTICSEARCH_ENABLE_REST_TLS: false
      ELASTICSEARCH_LOCK_ALL_MEMORY: true
      ELASTICSEARCH_HEAP_SIZE: 1g
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail --user elastic:qwerty localhost:9200/_cluster/health?local=true || exit 1" ]
      interval: 20s
      timeout: 20s
      retries: 10
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    image: "bitnami/kibana:8.17.1"
    container_name: kibana
    environment:
      KIBANA_ELASTICSEARCH_URL: elastic
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:5601/api/status || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 10
    ports:
      - "5601:5601"
    volumes:
      - kibana:/usr/share/kibana/data
    depends_on:
      elastic:
        condition: service_healthy

volumes:
  elastic:
  kibana:
