services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  keycloak:
    image: "bitnami/keycloak:26"
    container_name: keycloak
    environment:
      KEYCLOAK_HTTP_PORT: 8100
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: program
      KEYCLOAK_DATABASE_PASSWORD: "test"
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: true
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.profile.feature.scripts=enabled"
    ports:
      - "8100:8100"
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:9000/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - keycloak:/bitnami/keycloak
      - ./keycloak/:/docker-entrypoint-initdb.d/
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  keycloak:
  postgres:
