services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  openldap:
    image: "bitnami/openldap:2.6"
    container_name: openldap
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_ADMIN_DN: cn=admin,dc=example,dc=org
      LDAP_ROOT: dc=example,dc=org
    healthcheck:
      test: [ "CMD-SHELL", "ldapsearch -H ldapi:/// -b dc=example,dc=org cn > /dev/null" ]
      interval: 15s
      retries: 5
      timeout: 5s
    ports:
      - "1389:1389"
      - "1636:1636"
    volumes:
      - openldap:/bitnami/openldap
      - ./openldap:/ldifs

  openldap-admin:
    image: "osixia/phpldapadmin:0.9.0"
    container_name: openldap-admin
    ports:
      - "8000:80"
    healthcheck:
      test: "curl --fail http://localhost || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./openldap-admin/.env.yaml:/container/environment/01-custom/env.yaml
    depends_on:
      openldap:
        condition: service_started

  keycloak:
    image: "bitnami/keycloak:26"
    container_name: keycloak
    environment:
      KEYCLOAK_HTTP_PORT: 8100
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: program
      KEYCLOAK_DATABASE_PASSWORD: "test"
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: true
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.profile.feature.scripts=enabled"
    ports:
      - "8100:8100"
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:9000/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - keycloak:/bitnami/keycloak
      - ./keycloak/:/docker-entrypoint-initdb.d/
    depends_on:
      postgres:
        condition: service_healthy
      openldap:
        condition: service_healthy

volumes:
  keycloak:
  openldap:
  postgres:
