version: "3.9"
services:
  echo-server:
    image: romanowalex/echo-server:v2.0
    container_name: echo-server
    environment:
      SPRING_PROFILES_ACTIVE: simple
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8080/manage/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
