global:
  scrape_interval: 5s

scrape_configs:
  - job_name: cAdvisor
    static_configs:
      - targets: [ "cadvisor:8080" ]

  - job_name: Node Exporter
    static_configs:
      - targets: [ "node-exporter:9100" ]
