services:
  jaeger:
    image: "jaegertracing/jaeger:2.2.0"
    command: [ "--config", "/etc/jaeger/config.yml" ]
    container_name: jaeger
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686" ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "16686:16686"
      - "4318:4318"
    volumes:
      - "./jaeger/simple-config.yml:/etc/jaeger/config.yml"
