x-minio-common: &minio-common
  image:
    minio/minio:latest
  command: server --console-address ":9001" http://minio-{1...2}/data
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: program
    MINIO_ROOT_PASSWORD: qwerty123
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio-1:
    <<: *minio-common
    hostname: minio-1
    volumes:
      - data1:/data

  minio-2:
    <<: *minio-common
    hostname: minio-2
    volumes:
      - data2:/data

  nginx:
    image: nginx:1.25-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: "curl --fail http://localhost:9001 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      minio-1:
        condition: service_healthy
      minio-2:
        condition: service_healthy

volumes:
  data1:
  data2:
