#!/usr/bin/env bash

readonly CONTAINER_IP=$(hostname --ip-address)

export PATRONI_NAME="${PATRONI_NAME:-$(hostname)}"
export PATRONI_RESTAPI_CONNECT_ADDRESS="${CONTAINER_IP}:8008"
export PATRONI_RESTAPI_LISTEN="${CONTAINER_IP}:8008"
export PATRONI_POSTGRESQL_CONNECT_ADDRESS="${CONTAINER_IP}:5432"
export PATRONI_POSTGRESQL_LISTEN="${CONTAINER_IP}:5432"
export PATRONI_SUPERUSER_USERNAME=${POSTGRES_USER:-postgres}
export PATRONI_SUPERUSER_PASSWORD=${POSTGRES_PASSWORD:-postgres}

exec /usr/local/bin/patroni /etc/patroni.yml
